### ISSUE TITLE
how to generate the ISAID_train_512.json

### ISSUE THREAD

**Issue by ZiMo-Chen** [heshitian/PLUG#2]
how to generate the ISAID_train_512.json ?

**Comment by heshitian** [comment]
We use preprocess/preprocess.py in the iSAID_Devkit toolbox to generate the iSAID_train_512.json.

**Comment by ZiMo-Chen** [comment]
> We use preprocess/preprocess.py in the iSAID_Devkit toolbox to generate the iSAID_train_512.json.

thank you for you reply!
can you please tell me how to generate the DOTA_train_512?
Why are ISAID_train_512.json and DOTA_train_512.json used, what is the role of the two, and how are they different

**Comment by ZihangZhan** [comment]
Where is preprocess/preprocess.py？
