### ISSUE TITLE
cannot import name 'dijkstra_image' from 'pydijkstra'

### ISSUE THREAD

**Issue by Scienthusiasts** [heshitian/PLUG#6]
I just run pip install pydijkstra and the error raised, is your pydijkstra use this lib:https://pypi.org/project/pydijkstra/#description or something else?

**Comment by jqp-code-ke** [comment]
me too

**Comment by Scienthusiasts** [comment]
The author used pydijkstra lib from PSPS, the code and installation can be found at https://github.com/BraveGroup/PSPS.git
